if City.count.zero?
  City.create([
                { name: "Alaminos", state_id: 2 },
                { name: "Angeles", state_id: 5 },
                { name: "Antipolo", state_id: 6 },
                { name: "Bacolod", state_id: 9 },
                { name: "Bacoor", state_id: 6 },
                { name: "Bago", state_id: 9 },
                { name: "Baguio", state_id: 3 },
                { name: "Bais", state_id: 10 },
                { name: "Balanga", state_id: 5 },
                { name: "Batac", state_id: 2 },
                { name: "Batangas City", state_id: 6 },
                { name: "Bayawan", state_id: 10 },
                { name: "Baybay", state_id: 11 },
                { name: "Bayugan", state_id: 16 },
                { name: "Biñan", state_id: 6 },
                { name: "Bislig", state_id: 16 },
                { name: "Bogo", state_id: 10 },
                { name: "Borongan", state_id: 11 },
                { name: "Butuan", state_id: 16 },
                { name: "Cabadbaran", state_id: 16 },
                { name: "Cabanatuan", state_id: 5 },
                { name: "Cabuyao", state_id: 6 },
                { name: "Cadiz", state_id: 9 },
                { name: "Cagayan de Oro", state_id: 13 },
                { name: "Calamba", state_id: 6 },
                { name: "Calapan", state_id: 7 },
                { name: "Calbayog", state_id: 11 },
                { name: "Calooocan", state_id: 1 },
                { name: "Candon", state_id: 2 },
                { name: "Canlaon", state_id: 10 },
                { name: "Carcar", state_id: 10 },
                { name: "Catbalogan", state_id: 11 },
                { name: "Cauayan", state_id: 4 },
                { name: "Cavite City", state_id: 6 },
                { name: "Cebu City", state_id: 10 },
                { name: "Cotabato City", state_id: 15 },
                { name: "Dagupan", state_id: 2 },
                { name: "Danao", state_id: 10 },
                { name: "Dapitan", state_id: 12 },
                { name: "Dasmariñas", state_id: 6 },
                { name: "Davao City", state_id: 14 },
                { name: "Digos", state_id: 14 },
                { name: "Dipolog", state_id: 12 },
                { name: "Dumaguete", state_id: 10 },
                { name: "El Salvador", state_id: 13 },
                { name: "Escalante", state_id: 9 },
                { name: "Gapan", state_id: 5 },
                { name: "General Santos", state_id: 15 },
                { name: "General Trias", state_id: 6 },
                { name: "Gingoog", state_id: 13 },
                { name: "Guihulngan", state_id: 10 },
                { name: "Himamaylan", state_id: 9 },
                { name: "Ilagan", state_id: 4 },
                { name: "Iligan", state_id: 13 },
                { name: "Iloilo City", state_id: 9 },
                { name: "Imus", state_id: 6 },
                { name: "Iriga", state_id: 8 },
                { name: "Isabela", state_id: 12 },
                { name: "Kabankalan", state_id: 9 },
                { name: "Kidapawan", state_id: 15 },
                { name: "Koronodal", state_id: 15 },
                { name: "La Carlota", state_id: 9 },
                { name: "Lamitan", state_id: 17 },
                { name: "Laoag", state_id: 2 },
                { name: "Lapu-lapu", state_id: 10 },
                { name: "Las Piñas", state_id: 1 },
                { name: "Legazpi", state_id: 8 },
                { name: "Ligao", state_id: 8 },
                { name: "Lipa", state_id: 6 },
                { name: "Lucena", state_id: 6 },
                { name: "Maasin", state_id: 11 },
                { name: "Mabalacat", state_id: 5 },
                { name: "Makati", state_id: 1 },
                { name: "Malabon", state_id: 1 },
                { name: "Malaybalay", state_id: 13 },
                { name: "Malolos", state_id: 5 },
                { name: "Mandaluyong", state_id: 1 },
                { name: "Mandaue", state_id: 10 },
                { name: "Manila", state_id: 1 },
                { name: "Marawi", state_id: 17 },
                { name: "Marikina", state_id: 1 },
                { name: "Masbate City", state_id: 8 },
                { name: "Mati", state_id: 14 },
                { name: "Meycauayan", state_id: 5 },
                { name: "Muñoz", state_id: 5 },
                { name: "Muntinlupa", state_id: 1 },
                { name: "Naga", state_id: 10 },
                { name: "Navotas", state_id: 1 },
                { name: "Olongapo", state_id: 5 },
                { name: "Ormoc", state_id: 11 },
                { name: "Oroquieta", state_id: 13 },
                { name: "Ozamiz", state_id: 13 },
                { name: "Pagadian", state_id: 12 },
                { name: "Palayan", state_id: 5 },
                { name: "Panabo", state_id: 14 },
                { name: "Parañaque", state_id: 1 },
                { name: "Pasay", state_id: 1 },
                { name: "Pasig", state_id: 1 },
                { name: "Passi", state_id: 9 },
                { name: "Puerto Princesa", state_id: 7 },
                { name: "Quezon City", state_id: 1 },
                { name: "Roxas", state_id: 9 },
                { name: "Sagay", state_id: 9 },
                { name: "Samal", state_id: 14 },
                { name: "San Carlos", state_id: 9 },
                { name: "San Carlos", state_id: 2 },
                { name: "San Fernando", state_id: 2 },
                { name: "San Fernando", state_id: 5 },
                { name: "San Jose", state_id: 5 },
                { name: "San jose del Monte", state_id: 5 },
                { name: "San juan", state_id: 1 },
                { name: "San Pablo", state_id: 6 },
                { name: "San Pedro", state_id: 6 },
                { name: "Santo Tomas", state_id: 6 },
                { name: "Santa Rosa", state_id: 6 },
                { name: "Santiago", state_id: 4 },
                { name: "Silay", state_id: 9 },
                { name: "Sipalay", state_id: 9 },
                { name: "Sorsogon City", state_id: 8 },
                { name: "Surigao City", state_id: 16 },
                { name: "Tabaco", state_id: 8 },
                { name: "Tabuk", state_id: 3 },
                { name: "Tacloban", state_id: 11 },
                { name: "Tacurong", state_id: 15 },
                { name: "Tagaytay", state_id: 6 },
                { name: "Tagbilaran", state_id: 10 },
                { name: "Taguig", state_id: 1 },
                { name: "Tagum", state_id: 14 },
                { name: "Talisay", state_id: 10 },
                { name: "Talisay", state_id: 9 },
                { name: "Tanauan", state_id: 6 },
                { name: "Tandag", state_id: 16 },
                { name: "Tangub", state_id: 13 },
                { name: "Tanjay", state_id: 10 },
                { name: "Tarlac City", state_id: 5 },
                { name: "Tayabas", state_id: 6 },
                { name: "Toledo", state_id: 10 },
                { name: "Trece Martires", state_id: 6 },
                { name: "Tuguegarao", state_id: 4 },
                { name: "Urdaneta", state_id: 2 },
                { name: "Valencia", state_id: 13 },
                { name: "Valenzuela", state_id: 1 },
                { name: "Victorias", state_id: 9 },
                { name: "Vigan", state_id: 2 },
                { name: "Zamboanga City", state_id: 12 }
              ])
  puts "Successfully seeded cities table... Proceeding..."
else
  puts "City table has already been seeded... Proceeding..."
end
